name: boneseg-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython
  - jupyterlab
  - notebook
  - h5py
  - pyqt
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scipy
      - plotly
      - torch
      - torchvision
      - scikit-learn
      - scikit-image
      - albumentations
      - tqdm